In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv(r"D:\DATA SCIENCE\data science\11. Deep Learning\Churn_Modelling.csv")


In [76]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
None


In [77]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [78]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [79]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [80]:
x=df.iloc[:,0:10].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [81]:
y=df.iloc[:,10].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [82]:
np.unique(x[:,1])

array(['France', 'Germany', 'Spain'], dtype=object)

In [83]:
np.unique(x[:,2])

array(['Female', 'Male'], dtype=object)

In [84]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [85]:
x[:,1]=le.fit_transform(x[:,1])

In [86]:
x[:,2]=le.fit_transform(x[:,2])

In [87]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [88]:
x1=sc.fit_transform(x)

In [89]:
x1

array([[-0.32622142, -0.90188624, -1.09598752, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-0.44003595,  1.51506738, -1.09598752, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-1.53679418, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.60498839, -0.90188624, -1.09598752, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.25683526,  0.30659057,  0.91241915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 1.46377078, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [90]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x1,y,test_size=0.2)

In [97]:
x_train.shape

(8000, 10)

In [98]:
x_test.shape

(2000, 10)

In [93]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [94]:
z=Sequential()

In [95]:
z.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
z.add(Dense(units = 6, kernel_initializer='uniform', activation='relu'))
z.add(Dense(units = 1, kernel_initializer='uniform', activation='sigmoid'))
z.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [96]:
z.fit(x_train,y_train, batch_size=10,epochs=15,)

Epoch 1/15
800/800 [==============================] - 4s 4ms/step - loss: 0.4966 - accuracy: 0.7961
Epoch 2/15
800/800 [==============================] - 3s 4ms/step - loss: 0.4199 - accuracy: 0.8098
Epoch 3/15
800/800 [==============================] - 3s 4ms/step - loss: 0.3986 - accuracy: 0.8159
Epoch 4/15
800/800 [==============================] - 3s 4ms/step - loss: 0.3801 - accuracy: 0.8307
Epoch 5/15
800/800 [==============================] - 3s 4ms/step - loss: 0.3681 - accuracy: 0.8503
Epoch 6/15
800/800 [==============================] - 3s 4ms/step - loss: 0.3617 - accuracy: 0.8526
Epoch 7/15
800/800 [==============================] - 3s 4ms/step - loss: 0.3575 - accuracy: 0.8547
Epoch 8/15
800/800 [==============================] - 3s 4ms/step - loss: 0.3559 - accuracy: 0.8551
Epoch 9/15
800/800 [==============================] - 3s 4ms/step - loss: 0.3536 - accuracy: 0.8555
Epoch 10/15
800/800 [==============================] - 3s 4ms/step - loss: 0.3523 - accuracy: 0.8551